# Generated by Django 4.1.3 on 2022-12-09 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 12, 9, 17, 26, 54, 529886, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
